name: Self-hosted Test

on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Verificando o runner
      run: |
        echo "Rodando no runner self-hosted!"
        hostname
        whoami

