name: Teste no Runner Self-hosted

on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Clonando repositório
      uses: actions/checkout@v4

    - name: Verificando arquivos clonados
      run: |
        echo "Arquivos do repositório:"
        ls -la
